In [0]:
Syntax of mapPartitions()
RDD.mapPartitions(f, preservesPartitioning=False)

def f(partitionData):
  perform heavy initializations like Databse connections
  for element in partitionData:
    perform operations for element in a partition
  return updated data
df.rdd.mapPartitions(f)

In [0]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('SparkByExamples.com').getOrCreate()
data = [('James','Smith','M',3000),
  ('Anna','Rose','F',4100),
  ('Robert','Williams','M',6200), 
]

columns = ["firstname","lastname","gender","salary"]
df = spark.createDataFrame(data=data, schema = columns)
df.show()

+---------+--------+------+------+
|firstname|lastname|gender|salary|
+---------+--------+------+------+
|    James|   Smith|     M|  3000|
|     Anna|    Rose|     F|  4100|
|   Robert|Williams|     M|  6200|
+---------+--------+------+------+

In [0]:
# This function calls for each partition
def reformat(partitionData):
    for row in partitionData:
        yield [row.firstname+","+row.lastname,row.gender,row.salary*10/100]

df2=df.rdd.mapPartitions(reformat).toDF(["name","gender","bonus"])
df2.show()

+---------------+------+-----+
|           name|gender|bonus|
+---------------+------+-----+
|    James,Smith|     M|300.0|
|      Anna,Rose|     F|410.0|
|Robert,Williams|     M|620.0|
+---------------+------+-----+

In [0]:
# Another method
def reformat(partitionData):
  updatedData = []
  for row in partitionData:
    name=row.firstname+","+row.lastname
    gender=row.gender
    bonus=row.salary*10/100
    updatedData.append([name,gender,bonus])
  return iter(updatedData)

df2=df.rdd.mapPartitions(reformat).toDF(["name","gender","bonus"])
df2.show()

+---------------+------+-----+
|           name|gender|bonus|
+---------------+------+-----+
|    James,Smith|     M|300.0|
|      Anna,Rose|     F|410.0|
|Robert,Williams|     M|620.0|
+---------------+------+-----+